CREATE DATABASE IF NOT EXISTS control_pases CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE control_pases;
CREATE TABLE IF NOT EXISTS alumnos (
 id_alumno INT AUTO_INCREMENT PRIMARY KEY,
 nombres VARCHAR(100) NOT NULL, apellidos VARCHAR(150) NOT NULL,
 matricula VARCHAR(30) NOT NULL UNIQUE, semestre VARCHAR(10) NOT NULL,
 grupo VARCHAR(20) NOT NULL, especialidad VARCHAR(120) NOT NULL,
 tutor VARCHAR(200) NOT NULL, ine LONGTEXT NULL,
 creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tutores (
 id_tutor INT AUTO_INCREMENT PRIMARY KEY,
 nombres VARCHAR(100) NOT NULL, apellidos VARCHAR(150) NOT NULL,
 alumno VARCHAR(250) NOT NULL, parentesco VARCHAR(60) NOT NULL,
 telefono VARCHAR(30) NULL, codigo VARCHAR(40) NOT NULL UNIQUE,
 creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS salidas (
 id_salida INT AUTO_INCREMENT PRIMARY KEY,
 alumno VARCHAR(250) NOT NULL, tutor VARCHAR(200) NOT NULL,
 parentesco VARCHAR(60) NOT NULL, fecha DATE NOT NULL,
 hora TIME NOT NULL, grupo VARCHAR(20) NOT NULL, motivo VARCHAR(250) NOT NULL,
 folio CHAR(4) NOT NULL UNIQUE, creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
